[tool.poetry]
name = "poetry-demov2"
version = "0.1.0"
description = "AIphaBiz Project"
authors = ["leonop <zicheng.leo@gmail.com>"]
readme = "README.md"
packages = [{ include = "eCallsAgent" }]

[tool.poetry.dependencies]
python = ">=3.9, <3.10"
aiohappyeyeballs = ">=2.4.4,<2.5.0"
aiohttp = ">=3.10.11,<3.11.0"
aiosignal = ">=1.3.1,<1.4.0"
anyio = ">=4.5.2,<4.6.0"
asttokens = "*"
async-timeout = ">=5.0.1,<5.1.0"
attrs = ">=25.1.0,<25.2.0"
backcall = "*"
bertopic = ">=0.16.4,<0.17.0"
bleach = ">=6.1.0,<6.2.0"
blis = ">=0.7.11,<0.8.0"
catalogue = ">=2.0.10,<2.1.0"
certifi = ">=2025.1.31,<2025.2.0"
charset-normalizer = ">=3.4.1,<3.5.0"
click = ">=8.1.8,<8.2.0"
cloudpickle = ">=3.1.1,<3.2.0"
comm = "*"
confection = ">=0.1.5,<0.2.0"
cycler = ">=0.12.1,<0.13.0"
cymem = ">=2.0.11,<2.1.0"
Cython = ">=0.29.32,<0.30.0"
debugpy = "*"
decorator = "*"
distro = ">=1.9.0,<1.10.0"
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl" }
exceptiongroup = ">=1.2.2,<1.3.0"
executing = "*"
filelock = ">=3.16.1,<3.17.0"
fonttools = ">=4.56.0,<4.57.0"
frozenlist = ">=1.5.0,<1.6.0"
fsspec = ">=2025.2.0,<2025.3.0"
gensim = ">=4.2.0,<4.3.0"
h11 = ">=0.14.0,<0.15.0"
hdbscan = ">=0.8.40,<0.9.0"
httpcore = ">=1.0.7,<1.1.0"
httpx = ">=0.28.1,<0.29.0"
huggingface_hub = ">=0.12.1,<0.13.0"
idna = ">=3.10,<3.11"
importlib_metadata = "*"
iniconfig = ">=2.0.0,<2.1.0"
ipykernel = "*"
ipython = "*"
ipywidgets = ">=8.1.5,<8.2.0"
jedi = "*"
Jinja2 = ">=3.1.5"
jiter = ">=0.8.2,<0.9.0"
joblib = ">=1.4.2,<1.5.0"
jupyter_client = "*"
jupyter_core = "*"
jupyterlab_widgets = ">=3.0.13,<3.1.0"
kaleido = "0.2.1"
kiwisolver = ">=1.4.7,<1.5.0"
langcodes = ">=3.3.0,<3.4.0"
llvmlite = ">=0.39.0,<0.40.0"
locket = ">=1.0.0,<1.1.0"
MarkupSafe = ">=2.1.5,<2.2.0"
matplotlib = ">=3.7.1,<3.8.0"
matplotlib-inline = "*"
mpmath = ">=1.3.0,<1.4.0"
multidict = ">=6.1.0,<6.2.0"
murmurhash = ">=1.0.12,<1.1.0"
narwhals = ">=1.28.0,<1.29.0"
nest_asyncio = "*"
networkx = ">=3.1"
nltk = ">=3.9.1"
numba = ">=0.56.0,<0.57.0"
numpy = ">=1.22.0,<1.24.0"
openai = ">=1.65.2,<1.66.0"
packaging = "*"
pandas = "1.5.3"
parso = "*"
partd = ">=1.4.1,<1.5.0"
pathlib_abc = ">=0.1.1,<0.2.0"
pathy = ">=0.11.0,<0.12.0"
pexpect = "*"
pickleshare = "*"
pillow = ">=10.4.0,<10.5.0"
platformdirs = "*"
plotly = ">=6.0.0,<6.1.0"
pluggy = ">=1.5.0,<1.6.0"
preshed = ">=3.0.9,<3.1.0"
prompt_toolkit = "*"
propcache = ">=0.2.0,<0.3.0"
psutil = "*"
ptyprocess = "*"
pure_eval = "*"
pyarrow = ">=14.0.1"
pydantic = ">=1.10.8,<1.11.0"
Pygments = "*"
pynndescent = ">=0.5.13,<0.6.0"
pyparsing = ">=3.1.4,<3.2.0"
pytest = ">=8.3.5,<8.4.0"
python-dateutil = "*"
pytz = ">=2025.1,<2025.2"
PyYAML = ">=6.0.2,<6.1.0"
pyzmq = "*"
regex = ">=2024.11.6,<2024.12.0"
requests = ">=2.32.3,<2.33.0"
safetensors = ">=0.5.3,<0.6.0"
scikit-learn = ">=1.3.2,<1.4.0"
scipy = ">=1.10.1,<1.11.0"
seaborn = ">=0.12.2,<0.13.0"
sentence-transformers = ">=2.2.2,<2.3.0"
sentencepiece = ">=0.2.0,<0.3.0"
six = "*"
smart-open = ">=6.4.0,<6.5.0"
sniffio = ">=1.3.1,<1.4.0"
spacy = ">=3.5.3,<3.6.0"
spacy-legacy = ">=3.0.12,<3.1.0"
spacy-loggers = ">=1.0.4,<1.1.0"
srsly = ">=2.4.8,<2.5.0"
stack-data = "*"
swifter = ">=1.3.4,<1.4.0"
sympy = ">=1.13.3"
tenacity = ">=9.0.0,<9.1.0"
thinc = ">=8.1.10,<8.2.0"
threadpoolctl = ">=3.5.0,<3.6.0"
tokenizers = ">=0.13.2,<0.14.0"
tomli = ">=2.2.1,<2.3.0"
toolz = ">=1.0.0,<1.1.0"
tornado = "*"
tqdm = ">=4.67.1,<4.68.0"
traitlets = "*"
transformers = ">=4.26.1,<4.28.0"
triton = "2.0.0"
typer = ">=0.7.0,<0.8.0"
typing-extensions = "*"
tzdata = ">=2025.1,<2025.2"
umap-learn = ">=0.5.3,<0.6.0"
urllib3 = ">=2.2.3,<2.3.0"
wasabi = ">=0.10.1,<0.11.0"
wcwidth = "*"
webencodings = ">=0.5.1,<0.6.0"
widgetsnbextension = ">=4.0.13,<4.1.0"
yarl = ">=1.15.2,<1.16.0"
zipp = ">=3.20.2,<3.21.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


